name: Deploy Lambda Project

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install zip
      run: sudo apt-get update && sudo apt-get install zip -y

    - name: Install Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
        sudo add-apt-repository "deb https://apt.releases.hashicorp.com ${HASHICORP_RELEASE} main"
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg -o /etc/apt/trusted.gpg.d/hashicorp.asc
        sudo apt-get update && sudo apt-get install terraform

    - name: Zip Lambda Function and set output
      id: zip_lambda
      run: |
        cd lambda
        zip ../lambda.zip handler.py
        cd ..
        echo "zip_name=lambda.zip" >> $GITHUB_OUTPUT

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve
